import { Router } from 'express';
import authRoutes from './auth.js';
import studentRoutes from './students.js';
import teacherRoutes from './teachers.js';
import adminRoutes from './admins.js';
import classRoutes from './classes.js';
import attendanceRoutes from './attendance.js';
import examRoutes from './exams.js';
import feeRoutes from './fees.js';
import resultRoutes from './results.js';
import migrationRoutes from './migration.js';
import settingsRoutes from './settings.js';
import announcementRoutes from './announcements.js';
import googleFormRoutes from './googleForm.js';
import staffCheckInRoutes from './staffCheckIn.js';
import exportRoutes from './export.js';
import adminActionRoutes from './adminActions.js';
import pendingPicChangeRoutes from './pendingPicChanges.js';
import picUserRoutes from './picUsers.js';
import picRecycleBinRoutes from './picRecycleBin.js';
import archiveRoutes from './archive.js';
import paymentRoutes from './payments.js';
import paymentGatewaySettingsRoutes from './paymentGatewaySettings.js';
import toyyibPayRoutes from './toyyibpay.js';
import contactRoutes from './contact.js';
import ibRoutes from './ib.js';
import userRoutes from './users.js';
import receiptRoutes from './receipts.js';
import maintenanceRoutes from './maintenance.js';
const router = Router();

router.use('/auth', authRoutes);
router.use('/students', studentRoutes);
// Teacher registration route is now handled INSIDE teacherRoutes (before auth middleware)
router.use('/teachers', teacherRoutes);
router.use('/admins', adminRoutes);
router.use('/classes', classRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/exams', examRoutes);
router.use('/fees', feeRoutes);
router.use('/results', resultRoutes);
router.use('/migration', migrationRoutes);
router.use('/settings', settingsRoutes);
router.use('/announcements', announcementRoutes);
router.use('/google-form', googleFormRoutes);
router.use('/staff-checkin', staffCheckInRoutes);
router.use('/export', exportRoutes);
router.use('/admin-actions', adminActionRoutes);
router.use('/pending-pic-changes', pendingPicChangeRoutes);
router.use('/pic-users', picUserRoutes);
router.use('/pic-recycle-bin', picRecycleBinRoutes);
router.use('/archive', archiveRoutes);
router.use('/payments', paymentRoutes);
router.use('/payment-gateways', paymentGatewaySettingsRoutes);
router.use('/toyyibpay', toyyibPayRoutes);
router.use('/contact', contactRoutes);
router.use('/ib', ibRoutes);
router.use('/users', userRoutes);
router.use('/receipts', receiptRoutes);
router.use('/maintenance', maintenanceRoutes);

export default router;
